CREATE TABLE TB_REQSYS_TEAMS_OUTBOX (
    ID_EVENTO UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CORRELATION_ID VARCHAR(100) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(200) NOT NULL UNIQUE,
    TASK_ID VARCHAR(200) NOT NULL,
    DESTINATARIO VARCHAR(200) NOT NULL,
    STATUS_EVENTO VARCHAR(50) NOT NULL,
    MENSAGEM_HASH VARCHAR(128) NOT NULL,
    MENSAGEM_MARKDOWN NVARCHAR(MAX) NOT NULL,
    QT_TENTATIVAS INT NOT NULL DEFAULT 0,
    ERRO_RESUMIDO VARCHAR(1000) NULL,
    DT_CRIACAO DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    DT_ULTIMA_TENTATIVA DATETIMEOFFSET NULL
);

CREATE INDEX IX_REQSYS_TEAMS_OUTBOX_CORRELATION
ON TB_REQSYS_TEAMS_OUTBOX (CORRELATION_ID);

CREATE INDEX IX_REQSYS_TEAMS_OUTBOX_STATUS
ON TB_REQSYS_TEAMS_OUTBOX (STATUS_EVENTO);

CREATE INDEX IX_REQSYS_TEAMS_OUTBOX_STATUS_TENTATIVA
ON TB_REQSYS_TEAMS_OUTBOX (STATUS_EVENTO, QT_TENTATIVAS, DT_CRIACAO);
