CREATE TABLE TB_REQSYS_TEAMS_OUTBOX (
    ID_EVENTO UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CORRELATION_ID VARCHAR(100) NOT NULL,
    IDEMPOTENCY_KEY VARCHAR(200) NOT NULL UNIQUE,
    TASK_ID VARCHAR(200) NOT NULL,
    DESTINATARIO VARCHAR(200) NOT NULL,
    STATUS_EVENTO VARCHAR(50) NOT NULL,
    MENSAGEM_HASH VARCHAR(128) NOT NULL,
    DT_CRIACAO DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);

CREATE INDEX IX_REQSYS_TEAMS_OUTBOX_CORRELATION
ON TB_REQSYS_TEAMS_OUTBOX (CORRELATION_ID);

CREATE INDEX IX_REQSYS_TEAMS_OUTBOX_STATUS
ON TB_REQSYS_TEAMS_OUTBOX (STATUS_EVENTO);
